-- Logging table for the debugging framework.

CREATE TABLE debug_log
(
	log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  	log_time    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  	module_name VARCHAR2(100),
  	line_no     NUMBER,
  	log_level   VARCHAR2(10),
  	log_message VARCHAR2(4000),
  	session_id  VARCHAR2(50) DEFAULT SYS_CONTEXT('USERENV', 'SESSIONID')
);

-- Index for reading logs by session/time
CREATE INDEX debug_log_ix1 ON debug_log(session_id, log_time);

--FOR TESTING:
--DROP PACKAGE debug_utils;
--DROP TABLE debug_log;